### PR TITLE
[SER-287] Env cleanup

### PR DESCRIPTION
**Pull request by mountHouli**
## Jira Tickets
- https://jira.amida.com/browse/SER-287
- https://jira.amida.com/browse/SER-285

## Changes
- Removes `.env.production` (it was completely unused; formerly was an experiment by @mountHouli).
- Changes `PUSH_NOTIFICATIONS_SERVICE_USER_USERNAME` to something memorable (makes life easier).
- Changes `PUSH_NOTIFICATIONS_SERVICE_USER_PASSWORD` in `.env.example` to something that works in all environments (no longer has a leading `@` character) and something memorable (makes life easier).
- Changes `NOTIFICATION_SERVICE_AUTOMATED_TEST_JWT` to match the new `PUSH_NOTIFICATIONS_SERVICE_USER_USERNAME`

## To Test
`yarn test`

### CODE REVIEW

**Review by orndorffgrant — CHANGES_REQUESTED** [review]
Bad news - Looks like the jwt encoder we used did add an expiration time even though we didn't tell it to. So the tests are now failing :(

**Comment by orndorffgrant** [comment]
This would be a bit more involved and probably out of scope, but instead of accepting a jwt as an environment variable, the test suite could just create a jwt itself before running since it has the secret and we're using symmetric auth

**Comment by rmharrison** [comment]
I'm opting to regenerate the token w/o `exp`, 'cause expedient.
- Used https://jwt.io/

To demonstrate @orndorffgrant 's point...

Old pay load, no `exp`
```
{
  "username": "oucuYaiN6pha3ahphiiT",
  "iat": 1516239022
}
```

New payload, with `exp` (Wed May 29 2019)
```
{
  "username": "pnsu@amida.com",
  "iat": 1516239022,
  "jti": "cd9d2b91-9101-45d1-8c73-c5fe980c7448",
  "exp": 1559157580
}
```

**Review by rmharrison — APPROVED** [review]

**Review by orndorffgrant — APPROVED** [review]
Worked well!

**Pull request merged**
