### PR TITLE
Dockerfile changes per DEVOPS-365

### PR DESCRIPTION
**Pull request by mountHouli**
If this PR fixes a bug, you _must_ add test cases representative of the bug.
#### What's this PR do?
Improves the Dockerfile and makes it conform to the other services' Dockerfiles per DEVOPS-365.

#### Related JIRA tickets:
https://jira.amida.com/browse/DEVOPS-365

#### How should this be manually tested?
`docker build -t SOME_TAG .`

It should build.

If you run it, it should work correctly.

### CODE REVIEW

**Comment by jmfadeley** [comment]
image
So I got this error when I switched branches and tried to run the Docker build straight out of the box. Afterwards, I ran a `yarn` locally, rebuilt and it built the image just fine. What exactly happened? I was under the impression that only the build inside the builder image matters, not local build. Or is there a dependency locally I'm not aware of?

**Comment by jmfadeley** [comment]
Heads up that the migration script is an oathbreaker.

image

**Comment by jmfadeley** [comment]
I'd definitely check that migration error, but the it's up on my docker and I'm getting `OK`s back from `/api/health-check`.

Commands that I used:
`docker run --name notification-db --network indaba-network -p 5433:5432 -e POSTGRES_USER=amida -e POSTGRES_PASSWORD=amida -e POSTGRES_DB=amida-notification-microservice postgres:9.6` (Note that this makes the database accessible on port 5433, probably not conflicting with your own service, so you can check the database which did populate with tables.) 

`docker run -p 4003:4003 --name amida-notification-microservice  --network indaba-network -v C:\Users\Odin\workspace\amida-notification-microservice\.env:/app/.env -e NOTIFICATION_SERVICE_PG_HOST=notification-db amida-notification-microservice`

**Comment by rmharrison** [comment]
@ jmfadeley
> I was under the impression that only the build inside the builder image matters, not local build. 

`COPY . /app/` copies your local directory into the Dockerfile, *except* explicitly ignored files/folders in `.dockerignore`

**Comment by rmharrison** [comment]
Fine to merge. Moving the migrations into sequelize is a perseverate issue.

**Comment by jmfadeley** [comment]
@mountHouli approved. You're good to go.

**Comment by mountHouli** [comment]
Whoah!!

**Pull request merged**
